### ISSUE TITLE
Game Crashes! (1.12.2)

### ISSUE THREAD

**Issue by RedGreenBlue09** [Quintinity/better-ping#1]
Hi, please help me. I tried to install this mod and it crashed.

Here is the crash report (Mod list and info inside)
https://pastebin.com/xNf3ubzT

Thanks.

**Comment by vladmarica** [comment]
Hi, it looks like you have **[Indicatia](https://www.curseforge.com/minecraft/mc-mods/indicatia)** installed as well. This mod is not compatible with it, you'll have to choose one or the other. Sorry!
