### ISSUE TITLE
Add 1.18 support

### ISSUE THREAD

**Issue by vladmarica** [Quintinity/better-ping#11]
Minecraft 1.18 is out now, so this mod needs to be updated

**Comment by rex706** [comment]
I would also love to see this mod updated to 1.18

**Comment by Lawerencium** [comment]
yup, me too, very usefull mod. Please update BetterPingDisplay to 1.18.x

**Comment by vladmarica** [comment]
The 1.18 version of this mod has been released: https://www.curseforge.com/minecraft/mc-mods/better-ping-display/files/3596827
