### ISSUE TITLE
1.18.2 Request

### ISSUE THREAD

**Issue by CDAGaming** [Quintinity/better-ping#14]
As the title says, just wondering if a release could be pushed or tagged?

**Comment by rostikmak** [comment]
1.18.2 add please. If you not very busy of course.
Thanks for this helpful mod =)

**Comment by vladmarica** [comment]
Available here: https://www.curseforge.com/minecraft/mc-mods/better-ping-display/files/3735839

**Comment by rostikmak** [comment]
Thanks a lot! Have nice day
