### ISSUE TITLE
[Feature request] Please port this mod to fabric

### ISSUE THREAD

**Issue by sphings79** [Quintinity/better-ping#2]
Hi,

would be great to see this mod on fabric :)

regards

sphings

**Comment by vladmarica** [comment]
I'll look into it. It should be relatively simple.

**Comment by vladmarica** [comment]
I've ported this mod to Fabric for Minecraft 1.15.2.

- [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric)
- [Source code](https://github.com/vladmarica/better-ping-display-fabric)

The Fabric version for 1.16 will be released once 1.16.3 is released and Fabric is updated for that version.
