### ISSUE TITLE
Thank you! ...and is there a 1.20.4 version planned?

### ISSUE THREAD

**Issue by XavierBit** [Quintinity/better-ping#21]
It would make me happy to see how crap my ping is :)

**Comment by SA64BD** [comment]
waiting for 1.20.4 :)

**Comment by vladmarica** [comment]
Closed in 389a98bef51a9ac1f07a0c8f1e90634987ea00e7.

Modrinth: https://modrinth.com/mod/better-ping-display/version/1.20.4-1.1
CurseForge: https://curseforge.com/minecraft/mc-mods/better-ping-display/files/5048840
